commit

diff --git a/.github/workflows/new_workflow2.yml b/.github/workflows/new_workflow2.yml
--- a/.github/workflows/new_workflow2.yml
+++ b/.github/workflows/new_workflow2.yml
@@ -1,4 +1,4 @@
-name: Reopen Issue when code changes requested
+name: Reopen issue when code changes requested
 
 on:
   pull_request:
@@ -32,12 +32,14 @@ jobs:
           echo "Trying to reopen issue..."
           echo "Issue number: $ISSUE_NUMBER"
           
-          close_issue=$(gh issue close $ISSUE_NUMBER --repo ${{ github.repository }})
-          response_code=$?
-          
-          if [ "$response_code" -ne 0 ]; then
-            echo "ERROR: Request failed with exit status ${response_code}!"
-            exit 1
+          if [ "$ISSUE_STATE" = "OPEN" ]; then
+            close_issue=$(gh issue close $ISSUE_NUMBER --repo ${{ github.repository }})
+            response_code=$?
+            
+            if [ "$response_code" -ne 0 ]; then
+              echo "ERROR: Request failed with exit status ${response_code}!"
+              exit 1
+            fi
           fi
 
           reopen_issue=$(gh issue reopen $ISSUE_NUMBER --repo ${{ github.repository }})
