commit

diff --git a/.github/workflows/new_workflow2.yml b/.github/workflows/new_workflow2.yml
--- a/.github/workflows/new_workflow2.yml
+++ b/.github/workflows/new_workflow2.yml
@@ -30,6 +30,14 @@ jobs:
         run: |
           echo "Trying to reopen issue..."
           echo "Issue number: $ISSUE_NUMBER"
+          
+          close_issue=$(gh issue close $ISSUE_NUMBER --repo ${{ github.repository }})
+          response_code=$?
+          
+          if [ "$response_code" -ne 0 ]; then
+            echo "ERROR: Request failed with exit status ${response_code}!"
+            exit 1
+          fi
 
           reopen_issue=$(gh issue reopen $ISSUE_NUMBER --repo ${{ github.repository }})
           response_code=$?
